set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})

set(CPACK_GENERATOR "DEB")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Caio Piccirillo <caiopiccirillo@gmail.com>")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Controller for furuta pendulum")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS¶ "ON")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "") # Add dependencies here
